cloud_id                 = "b1g5oisudfns3c0u64o7"
folder_id                = "b1g8fm7t7bsh1biji6v8"
zone                     = "ru-central1-a"
app_disk_image           = "fd8v51matgprsco0msae"
db_disk_image            = "fd8jeq59gaqlqiseppdl"
public_key_path          = "../.ssh/ubuntu.pub"
subnet_id                = "e9brqqa8p3ddmgihcfbu"
service_account_key_file = "key.json"
