---
driver:
  name: vagrant
  provider:
    name: vmware_desktop
lint: yamllint
platforms:
  - name: instance
    box: bento/ubuntu-20.04
    # memory: 512
    # interfaces:
    #   - network_name: private_network
    #     ip: 10.10.10.50
provisioner:
  name: ansible
  lint:
    name: ansible-lint
